version: '3'
services:
  express-app:
    image: back-image
    container_name: express-container
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo-db

  react-app:
    image: front-image
    container_name: react-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - express-app
