version: '3'
services:
  express-app:
    image: backend-image
    container_name: express-container
    build:
      context: ./back-End
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3005"

  react-app:
    image: frontend-image
    container_name: react-container
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - express-app
